### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by dd-stack** [dd-stack/pre-project-react-tutorial#1]
### 만들고자 하는 기능
Todo 생성 기능

### 해당 기능을 구현하기 위해 할 일
1. [ ]  todoCreate 컴포넌트 생성
2. [ ]  state와 함수 작성
3. [ ] 로컬 스토리지 구현

### 예상 작업 시간
3h

### (기타) 참고 사항
- Assigness: 해당 태스크를 맡은 사람을 지정 ( assign yourself 를 누르면 자신의 태스크로 만들 수 있음 )
- Labels: 태스크 카드에 라벨링을 할 수 있음
- Projects: Projects를 지정할 수 있음.
- Milestone: 마일스톤을 지정할 수 있음
